/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.danielcastellani.gerenciadordetarefas.gui;

import br.danielcastellani.gerenciadordetarefas.controle.TelaProjetoListagemControlador;

/**
 *
 * @author Daniel
 */
public class TelaProjetoListagem extends javax.swing.JInternalFrame {

    TelaProjetoListagemControlador controlador;
    private TelaProjeto telaProjeto;

    /**
     * Creates new form TelaProjetoListagem
     */
    public TelaProjetoListagem() {
        initComponents();
        controlador = new TelaProjetoListagemControlador(this);
        controlador.listarProjetos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListagem = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Listagem de Projetos");

        panelListagem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelListagem.setAutoscrolls(true);
        panelListagem.setMinimumSize(new java.awt.Dimension(200, 0));

        javax.swing.GroupLayout panelListagemLayout = new javax.swing.GroupLayout(panelListagem);
        panelListagem.setLayout(panelListagemLayout);
        panelListagemLayout.setHorizontalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        panelListagemLayout.setVerticalGroup(
            panelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelListagem;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelListagem
     */
    public javax.swing.JPanel getPanelListagem() {
        return panelListagem;
    }

    /**
     * @param panelListagem the panelListagem to set
     */
    public void setPanelListagem(javax.swing.JPanel panelListagem) {
        this.panelListagem = panelListagem;
    }

    /**
     * @return the telaProjeto
     */
    public TelaProjeto getTelaProjeto() {
        return telaProjeto;
    }

    /**
     * @param telaProjeto the telaProjeto to set
     */
    public void setTelaProjeto(TelaProjeto telaProjeto) {
        this.telaProjeto = telaProjeto;
    }
}
